export const menuOptions = [
  {
    name: "Inicio",
    url: "/",
    showHeader: true,
    showFooter: false,
    showMisc: false,
    target: "_self",
  },
  {
    name: "Trabajos",
    url: "/portafolio",
    showHeader: true,
    showFooter: true,
    showMisc: false,
    target: "_self",
  },
  {
    name: "Proyectos",
    url: "/proyectos",
    showHeader: true,
    showFooter: true,
    showMisc: false,
    target: "_self",
  },
  {
    name: "Podcast",
    url: "/podcast",
    showHeader: true,
    showFooter: true,
    showMisc: false,
    target: "_self",
  },
  {
    name: "Contacto",
    url: "/contacto",
    showHeader: true,
    showFooter: false,
    showMisc: true,
    target: "_self",
  },
  {
    name: "Blog",
    url: "https://creatyum.media",
    showHeader: true,
    showFooter: true,
    showMisc: false,
    target: "_blank",
  },
  {
    name: "Privacidad",
    url: "/privacidad",
    showHeader: false,
    showFooter: false,
    showMisc: true,
    target: "_self",
  },
  {
    name: "Términos de uso",
    url: "/terminos",
    showHeader: false,
    showFooter: false,
    showMisc: true,
    target: "_self",
  },
];
