export const menuOptions = [
  {
    id: 1,
    name: "Inicio",
    url: "/",
    showHeader: true,
    showFooter: false,
    showMisc: false,
    target: "_self",
  },
  {
    id: 2,
    name: "Trabajos",
    url: "/trabajos",
    showHeader: true,
    showFooter: true,
    showMisc: false,
    target: "_self",
  },
  {
    id: 3,
    name: "Proyectos",
    url: "/proyectos",
    showHeader: true,
    showFooter: true,
    showMisc: false,
    target: "_self",
  },
  {
    id: 4,
    name: "Podcast",
    url: "/podcast",
    showHeader: true,
    showFooter: true,
    showMisc: false,
    target: "_self",
  },
  {
    id: 5,
    name: "Ale",
    url: "/alejandro",
    showHeader: true,
    showFooter: false,
    showMisc: true,
    target: "_self",
  },
  {
    id: 6,
    name: "Blog",
    url: "https://creatyum.media",
    showHeader: true,
    showFooter: true,
    showMisc: false,
    target: "_blank",
  },
  {
    id: 7,
    name: "Privacidad",
    url: "/privacidad",
    showHeader: false,
    showFooter: false,
    showMisc: true,
    target: "_self",
  },
  {
    id: 8,
    name: "Términos de uso",
    url: "/terminos",
    showHeader: false,
    showFooter: false,
    showMisc: true,
    target: "_self",
  },
];
